#!/usr/bin/env bash
# Build cogent3.org into docs/.
#
# The site is ONE quarto project. The cogent3 doc tree is composed into doc/ and
# rendered under this repo's doc/_quarto.yml, which is the single source of
# truth for styling, navigation and organisation. cogent3's own doc/_quarto.yml
# is deliberately excluded from the copy -- that file exists so the cogent3 repo
# can build and test its docs in isolation, and letting it reach the site build
# is what previously gave the site two navbars, two sidebars and two search
# indexes.
#
#   ./build.sh                            from the pinned submodule
#   C3_REPO=/path/to/cogent3 ./build.sh   from another checkout
#   ./build.sh --skip-compose             reuse the already-composed doc/ tree
#   ./build.sh --skip-quartodoc           skip regenerating the API reference
#
# QUARTO may point at a quarto binary; CI sets it from the quarto-dev action so
# that no network install happens there.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

C3_REPO="${C3_REPO:-$here/doc/cogent3}"
C3_DOC="${C3_DOC:-$C3_REPO/doc}"
SITE="$here/doc" # the quarto project root

skip_compose=0
skip_quartodoc=0
for arg in "$@"; do
  case "$arg" in
    --skip-compose) skip_compose=1 ;;
    --skip-quartodoc) skip_quartodoc=1 ;;
    -h | --help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *)
      printf 'unknown argument: %s\n' "$arg" >&2
      exit 2
      ;;
  esac
done

if [[ -n "${QUARTO:-}" ]]; then
  QUARTO="$(command -v "$QUARTO")" || {
    echo "QUARTO is set but not executable" >&2
    exit 1
  }
else
  uv sync --group doc --quiet
  QUARTO="$here/.venv/bin/quarto"
  [[ -x "$QUARTO" ]] || {
    echo "no quarto at $QUARTO" >&2
    exit 1
  }
fi

if ((!skip_compose)); then
  [[ -f "$C3_DOC/_quarto.yml" ]] || {
    echo "no quarto project at $C3_DOC -- is the submodule initialised, or does" >&2
    echo "it predate the quarto migration? Set C3_REPO to a checkout that has one." >&2
    exit 1
  }
  echo "==> composing cogent3 docs from $C3_DOC"
  # --delete so a page removed upstream disappears here too. Excluding
  # _quarto.yml is the whole point: this repo's config governs the site.
  # --copy-links dereferences symlinks: in the submodule doc/data/fastq.txt
  # points into tests/, which would otherwise arrive here as a link with no
  # referent and fail the render when quarto copies resources.
  rsync -a --copy-links --delete \
    --exclude '_quarto.yml' \
    --exclude '_site/' --exclude '_freeze/' --exclude '.quarto/' \
    --exclude 'reference/' --exclude 'objects.json' \
    "$C3_DOC/" "$SITE/doc/"
  # The cogent3 pages address files relative to *their* project root -- 75 pages
  # read "data/..." and the gallery pages write thumbnails to "draw/...". Here
  # the project root is one level above their tree, so mirror each of their
  # top-level directories back to the root as a symlink. Execution then resolves
  # exactly as it does in the cogent3 repo, while everything still publishes
  # from /doc/..., leaving those URLs unchanged. Names already present in this
  # project (images/) win, so nothing of ours is shadowed.
  for dir in "$SITE"/doc/*/; do
    name="$(basename "$dir")"
    [[ -e "$SITE/$name" && ! -L "$SITE/$name" ]] && continue
    ln -sfn "doc/$name" "$SITE/$name"
  done
fi

# Guard against silent drift: every composed page must appear in the sidebar in
# doc/_quarto.yml, or it renders with no left nav and shifts out of alignment.
python3 - "$SITE" <<'PY'
import pathlib
import re
import sys

site = pathlib.Path(sys.argv[1])
config = (site / "_quarto.yml").read_text()
listed = set(re.findall(r"[\s-]\s*((?:doc/)?[\w./*-]+\.qmd)", config))


def covered(rel: str) -> bool:
    if rel in listed:
        return True
    # a glob entry such as doc/draw/aln/*.qmd covers this page
    return any(
        entry.endswith("*.qmd") and rel.startswith(entry[: -len("*.qmd")])
        for entry in listed
    )


missing = []
for path in sorted(site.glob("doc/**/*.qmd")):
    rel = str(path.relative_to(site))
    # quarto never renders underscore-prefixed files, so they need no entry
    if any(part.startswith("_") for part in rel.split("/")):
        continue
    # doc/reference/ is generated by quartodoc from the package's docstrings, so
    # it is not something anyone maintains in the sidebar. Those pages are
    # reached from reference/index.qmd and inherit the sidebar (it has no `id:`),
    # so they still render docked and consistent.
    if rel.startswith("doc/reference/"):
        continue
    if not covered(rel):
        missing.append(rel)
if missing:
    print(f"{len(missing)} composed page(s) missing from the sidebar in", file=sys.stderr)
    print("doc/_quarto.yml -- they would render with no left nav:", file=sys.stderr)
    for rel in missing[:20]:
        print(f"    {rel}", file=sys.stderr)
    if len(missing) > 20:
        print(f"    ... and {len(missing) - 20} more", file=sys.stderr)
    sys.exit(1)
PY

if ((!skip_quartodoc)); then
  # writes doc/reference/*.qmd and objects.json, which the render then needs
  echo "==> building the API reference"
  (cd "$SITE" && uv run --project "$C3_REPO" --group doc \
    quartodoc build --config _quarto.yml)
fi

echo "==> rendering the site"
QUARTO_PYTHON="$C3_REPO/.venv/bin/python" "$QUARTO" render "$SITE"

mkdir -p docs
# CNAME and .nojekyll are tracked and live only in docs/; excluding them keeps
# --delete from removing them (rsync does not delete excluded paths).
rsync -a --delete \
  --exclude '/CNAME' --exclude '/.nojekyll' \
  "$SITE/_site/" docs/

printf 'built %s\n' "$here/docs"
